"""
Scambus Python Client Library

Official Python client for Scambus - submit scam reports and subscribe to data streams.

This library enables you to:
- Submit scam reports via journal entries (phone calls, emails, text messages, detections)
- Search for identifiers, cases, and journal entries
- Create and consume export streams (HTTP polling and SSE)
- Receive real-time notifications and updates via WebSocket
- Manage your own cases, tags, and profile
"""

from .client import (
    ScambusClient,
    build_identifier_type_filter,
    build_combined_filter,
)
from .exceptions import (
    ScambusAPIError,
    ScambusAuthenticationError,
    ScambusNotFoundError,
    ScambusServerError,
    ScambusValidationError,
)
from .websocket_client import ScambusWebSocketClient
from .types import (
    FilterCriteria,
    IdentifierType,
    JournalEntryType,
    StreamDataType,
    TagLookup,
    StreamFilter,
    ViewFilter,
    ViewSortOrder,
)
from .models import (
    ActionDetails,
    ActivityCompleteDetails,
    AnalysisDetails,
    BankAccountDetails,
    Case,
    CaseComment,
    CaseIdentifierLinkDetails,
    CaseUpdateDetails,
    ConfidenceOperationDetails,
    ContactDetails,
    ConversationContinuationDetails,
    ConversationMessage,
    CryptoWalletDetails,
    CustodyEvent,
    DetectionDetails,
    EmailDetails,
    Evidence,
    ExportDetails,
    ExportStream,
    FailedIdentifier,
    Identifier,
    IdentifierConfidenceUpdate,
    IdentifierEmailDetails,
    IdentifierLookup,
    IdentifierStreamMessage,
    ImportDetails,
    JournalEntry,
    JournalEntryChildSummary,
    JournalEntryStreamMessage,
    KarmaAdjustmentDetails,
    KarmaBreakdown,
    KarmaComponent,
    Media,
    MessageAttachment,
    MessageIdentifierRef,
    NoteDetails,
    Notification,
    ObservationDetails,
    Passkey,
    PaymentTokenDetails,
    PhoneCallDetails,
    PhoneDetails,
    RedactionDetails,
    ResearchDetails,
    Session,
    SocialMediaDetails,
    StreamEvidenceInfo,
    StreamIdentifierInfo,
    StreamJournalEntryInfo,
    StreamOriginatorInfo,
    StreamTagInfo,
    Tag,
    TagOperationDetails,
    TagValue,
    TextConversationDetails,
    URLDetails,
    UpdateDetails,
    ValidationDetails,
    View,
    ZelleDetails,
    parse_identifier_details,
)

__version__ = "0.1.0"
__all__ = [
    "ScambusClient",
    "ScambusWebSocketClient",
    "build_identifier_type_filter",
    "build_combined_filter",
    "ScambusAPIError",
    "ScambusAuthenticationError",
    "ScambusValidationError",
    "ScambusNotFoundError",
    "ScambusServerError",
    "FilterCriteria",
    "IdentifierType",
    "JournalEntryType",
    "StreamDataType",
    "TagLookup",
    "StreamFilter",
    "ViewFilter",
    "ViewSortOrder",
    "JournalEntry",
    "JournalEntryChildSummary",
    "Identifier",
    "IdentifierLookup",
    "Evidence",
    "FailedIdentifier",
    "Media",
    "PhoneCallDetails",
    "EmailDetails",
    "TextConversationDetails",
    "ConversationContinuationDetails",
    "ConversationMessage",
    "MessageIdentifierRef",
    "MessageAttachment",
    "CustodyEvent",
    "DetectionDetails",
    "ImportDetails",
    "ExportDetails",
    "ValidationDetails",
    "ContactDetails",
    "ResearchDetails",
    "AnalysisDetails",
    "ActionDetails",
    "ObservationDetails",
    "NoteDetails",
    "UpdateDetails",
    "TagOperationDetails",
    "IdentifierConfidenceUpdate",
    "ConfidenceOperationDetails",
    "ActivityCompleteDetails",
    "RedactionDetails",
    "CaseUpdateDetails",
    "CaseIdentifierLinkDetails",
    "KarmaComponent",
    "KarmaBreakdown",
    "KarmaAdjustmentDetails",
    "Case",
    "CaseComment",
    "ExportStream",
    "IdentifierStreamMessage",
    "JournalEntryStreamMessage",
    "StreamTagInfo",
    "StreamJournalEntryInfo",
    "StreamIdentifierInfo",
    "StreamOriginatorInfo",
    "StreamEvidenceInfo",
    "Tag",
    "TagValue",
    "Notification",
    "Session",
    "Passkey",
    "View",
    # Identifier detail types
    "PhoneDetails",
    "IdentifierEmailDetails",
    "URLDetails",
    "BankAccountDetails",
    "CryptoWalletDetails",
    "SocialMediaDetails",
    "ZelleDetails",
    "PaymentTokenDetails",
    "parse_identifier_details",
]
